export const productsData = [
    {
      id: 1,
      name: 'Stylish wear',
      description: 'If you’re looking for starter Oxford shoes, these by Metro will surely serve you well. They’ve got a classic appearance with central lace-ups, low heels and round toes which makes them great for nearly any casual occasion. Crafted with upper, lining and insole in leather and rubber outsole, they’re beautifully made and are equally comfortable.',
      details: 'This super versatile, daily go-to” can be dressed up with casual daytime outfits such as walking, running or traveling.',
      image:'https://www.dropbox.com/s/e928cht0h5crcn4/shoe.png?raw=1',
      color:['red','yellow','black'],
      price:200,
      size:[5,6,7,8],
    },
    {
      id: 2,
      name: 'Running shoes',
      description: 'Whether you are running for fun or training for a marathon, the right running shoes provide the proper foundation for your entire body, can help prevent injuries and make it far more enjoyable to log those miles. Ultimately, the right pair will fit well from the start and complement your running style.',
      price: 300,
      details: 'You could wear these Oxfords with jeans and a nice jacket for a smart casual look.',
      image:'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5823.png',
      color:['red','yellow','orange'],
      size:[6,7,8,9],
    },
    {
      id: 3,
      name: 'Modren wear',
      description: 'This beautiful design will instantly upgrade your “worktime” outfit with rich, burnished leather while a cushioned, arch-support footbed offers all-day comfort. Also known as the Chelsea boots, featuring round toe with low heels and elasticated sides, makes them easy to slip on and off without laces or buckles.',
      price: 100,
      details: 'A good blazer will work great with a simple sweatshirt or tee underneath and some easy-to-match pleated trousers or jeans below for special events and office functions.',
      image:'http://pluspng.com/img-png/nike-shoe-png-nike-running-shoes-png-image-transparent-free-download-1200.png',
      color:['violet','green','black'],
      size:[7,8,9,10]
    },
    {
      id: 4,
      name: 'Ethinic wear',
      description: 'One way to flaunt your sophistication is through a pair of patent synthetic Oxford boots from Metro. This pair features the traditional Oxford lace-up construction, as well as comfortable lining and insoles, and is finished with a sleek almond toe shape and low heels. ',
      price: 450,
      details: 'A nice watch and a beautiful crisp white shirt paired with matching trousers is essential to get with these formal shoes or they are tough enough to be worn under a trucker jacket and jeans for office events or casual outings.',
      image:'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5827.png',
      color:['white','yellow','red'],
      size:[5,6,7,8],
    },
    {
      id: 5,
      name: 'Formal boots',
      description: 'Streamlined and elegantly designed, fall in love with these formal shoes, thanks to their thin loop of upper to outsole leather, subtle buckle, leather pull tab for on-and-off ease, low heel, round toe and a fastening zip.',
      price: 20,
      details: 'When worn with a suit, the ornamentation is hidden, which adds to the dressiness. Also, goes well with casual office looks.',
      image:'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5824.png',
      color:['blue','orange','black'],
      size:[7,8,9,10],
    },
    {
      id: 6,
      name: 'Iconic shoes',
      description: 'These formal shoes can be extremely versatile. Whether in jeans or a sharp three-piece suit, they gel right in and offer original visual interest. The superior quality footbed will deliver the necessary all-day comfort whether you are wearing these black formal shoes to work or for a weekend with family or friends.',
      price: 150,
      details: 'A good blazer will work great with a simple sweatshirt or tee underneath and some easy-to-match pleated trousers or jeans below for special events and office functions.',
      image:'https://www.freepnglogos.com/uploads/shoes-png/shoes-shoe-png-transparent-shoe-images-pluspng-37.png',
      color:['red','white','black'],
      size:[5,6,7,8],
    },
    // Add more products as needed
  ];